In [1]:
import sys
import numpy as np
import pygame
import math
import font

BLUE = 0,0,200
BLACK = 0,0,0
RED = 255,0,0
YELLOW = 255,255,0



def create_board():
    board = np.zeros((6,7))
    return board

def print_board(board):
    print(np.flip(board,0))

def is_valid_place(board,col):
    if board[5][col]==0:
        return True


def get_next_open_row(board,col):
    for r in range(ROW):
        if board[r][col]==0:
            return r 
        

def drop_piece(board,row,col,piece):
    board[row][col]= piece
    
def draw_board(board):
    for c in range(COL):
        for r in range(ROW):
            pygame.draw.rect(screen,BLUE,(int(c*SQUARESIZE),int(r*SQUARESIZE+SQUARESIZE),SQUARESIZE,SQUARESIZE))
            pygame.draw.circle(screen,BLACK,(int(c*SQUARESIZE+SQUARESIZE/2),int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)),RADIUS)
    for c in range(COL):
        for r in range(ROW):        
            if board[r][c]== 1:
                pygame.draw.circle(screen,RED,(int(c*SQUARESIZE+SQUARESIZE/2),height-int(r*SQUARESIZE+SQUARESIZE/2)),RADIUS)
            elif board[r][c]==2:
                pygame.draw.circle(screen,YELLOW,(int(c*SQUARESIZE+SQUARESIZE/2),height-int(r*SQUARESIZE+SQUARESIZE/2)),RADIUS)
    pygame.display.update()
    
def winning_move(board,piece):
    
    for c in range(COL-3):
        for r in range(ROW):
            if board[r][c]==piece and board[r][c+1]==piece and board[r][c+2] == piece and board[r][c+3]==piece:
                return True
            
    #check forf vertical win
    for c in range(COL):
        for r in range(ROW-3):
            if board[r][c]==piece and board[r+1][c]==piece and board[r+2][c] == piece and board[r+3][c]==piece:
                return True
            
    #check for positively diagonal win
    for c in range(COL-3):
        for r in range(ROW-3):
            if board[r][c]==piece and board[r+1][c+1]==piece and board[r+2][c+2] == piece and board[r+3][c+3]==piece:
                return True
            
    #check for negatively diagonal win
    for c in range(COL-3):
        for r in range(3,ROW):
            if board[r][c]==piece and board[r-1][c-1]==piece and board[r-2][c-2] == piece and board[r-3][c-3]==piece:
                return True




ROW = 6
COL = 7
board = create_board()
game_over = False
turn =0




pygame.init()

SQUARESIZE = 100
RADIUS = int(SQUARESIZE/2-8)
width = int(COL * SQUARESIZE)
height = int((ROW+1) * SQUARESIZE)

size = (width,height)
screen = pygame.display.set_mode(size)
draw_board(board)
pygame.display.update()

myfont = pygame.font.SysFont("monospace",75 )

while not game_over:
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
            
        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(screen,BLACK,(0,0,width,SQUARESIZE))
            posx = event.pos[0]
            if turn == 0:
                pygame.draw.circle(screen,RED,(posx,int(SQUARESIZE/2)),RADIUS)
            else:
                pygame.draw.circle(screen,YELLOW,(posx,int(SQUARESIZE/2)),RADIUS)
            pygame.display.update()
            
        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen,BLACK,(0,0,width,SQUARESIZE))
            if turn == 0:
                posx = event.pos[0]
                selection = int(math.floor(posx/SQUARESIZE))

                if is_valid_place(board,selection):
                    next_row = get_next_open_row(board,selection)
                    drop_piece(board,next_row,selection,1)

                if winning_move(board,1):
                    label = myfont.render("Player 1 wins",1,RED)
                    screen.blit(label,(40,10))
                    game_over = True
                   
                    

            else:
                posx = event.pos[0]
                selection = int(math.floor(posx/SQUARESIZE))
                
                if is_valid_place(board,selection):
                        next_row = get_next_open_row(board,selection)
                        drop_piece(board,next_row,selection,2)

                if winning_move(board,2):
                    label = myfont.render("Player 2 wins",1,YELLOW)
                    screen.blit(label,(40,10))
                    game_over = True
                    


            turn +=1
            turn = turn %2

            print_board(board)
            draw_board(board)
            
            if game_over:
                pygame.time.wait(3000)
                pygame.quit()






[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 1. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 1. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 2. 2. 1. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0.]
 [0. 2. 2. 1. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0.]
 [0. 2. 2.